#!/bin/bash
#              `.-/::/-``
#            .-/osssssssso/.               
#           :osyysssssssyyys+-              
#        `.+yyyysssssssssyyyyy+.           
#       `/syyyyyssssssssssyyyyys-`         
#      `/yhyyyyysss++ssosyyyyhhy/`         
#     .ohhhyyyyso++/+oso+syy+shhhho.       
#    .shhhhysoo++//+sss+++yyy+shhhhs.      
#   -yhhhhs+++++++ossso+++yyys+ohhddy:     
#  -yddhhyo+++++osyyss++++yyyyooyhdddy-    
# .yddddhso++osyyyyys+++++yyhhsoshddddy`   
#`odddddhyosyhyyyyyy++++++yhhhyosddddddo   
#.dmdddddhhhhhhhyyyo+++++shhhhhohddddmmh.  
#ddmmdddddhhhhhhhso++++++yhhhhhhdddddmmdy  
#dmmmdddddddhhhyso++++++shhhhhddddddmmmmh  
#-dmmmdddddddhhyso++++oshhhhdddddddmmmmd- 
# .smmmmddddddddhhhhhhhhhdddddddddmmmms. 
#   `+ydmmmdddddddddddddddddddmmmmdy/.     
#      `.:+ooyyddddddddddddyyso+:.`
#======================================================================================
#                               I3 IMPROVED TILING
# 
# Author  : Erik Dubois at http://www.erikdubois.be
# License : Distributed under the terms of GNU GPL version 2 or later
# 
# AS ALLWAYS, KNOW WHAT YOU ARE DOING.
#======================================================================================
#                               
# Interesting Sources : 
#
#
#======================================================================================

# Made to be installed on a BASE INSTALLATION OF ANTERGOS
# no desktop environment, no display manager - X11 not yet installed
# all kinds of programs are being used from different distro's but xfce4 is my preference.

1 KEYBOARD

sudo loadkeys be-latin1    in order to have azerty KEYBOARD

change also the following file to make it permanent

sudo nano /etc/vconsole.conf

change your keyboard from "be"  to "be-latin1"




2 INTERNET

no internet on lan 

sudo systemctl enable dhcpcd
sudo systemctl start dhcpcd



3 GET GIT

Git should be installed but if not ...

sudo pacman -S git




4 Downloading my settings from github

git clone https://github.com/erikdubois/i3wmarchdark




5 Move this directory to the right place

cp -r ~/i3wmarchdark/ ~/.i3/




6 installation of software


First part is all software in normal arch repo's.

~/.i3/installation/1_install_i3_core_vxx.sh

Second part is all software from aur repo's.

~/.i3/installation/2_install_i3_aur_repo_vxx.sh

####################################

A T T E N T I O N !!

At the moment of writing I am trying out i3-gaps-next available via aur and
can be found on github.

That's why we first install i3-wm and uninstall it lateron to get the "gaps" version.
Evaluate what you think is best.


####################################

7 Let linux know where the most important documents are

# depending on how far you are in your installation some of these files
# will not yet exist - you can not remove what is not there
# ignore the errors

~/.i3/installation/4_keep_all_here_vx.sh

# .xinitrc is the most important as it says to start i3 to the xserver.



My system has been build on the use of zsh.
It will only use the zsh files if you set zsh as a replacement to Bash.
I changed the files so that even if you keep bash you will boot up i3.


~/.i3/installation/5_zsh_vxx.sh
sudo chsh erik -s /bin/zsh

Type in your password.


If you need smb or sharing folders via the network. There is one more file.

~/.i3/installation/6_smb_vxx.sh


#======================================================================================

THIS IS A GREAT TIME TO REBOOT.

#======================================================================================



After login you should be in i3wm.


8 Change appearance

windowskey or Mod1 and d opens the menu

type  "lx"  and choose lxappearance
change to your liking



9 Font 

move the font to its right directory - workspace 8 has the file manager

mkdir ~/.fonts    #if necessary make directory First
cp ~/.i3/installation/fonts/fontawesome-webfont.ttf ~/.fonts/


10 Config apps

here are my personal preferences or plugins or ... 
use them or not
these are not essential to the installation


11 Change the look for qt4 applications

mod1+d and look for the program "qtconfig-qt4"
programs like spotify will change their submenu's to the qtk theme
choose same font as rest or a different one.


12 .config directory is owned by root 

a ticket has been filed at github regarding this matter
ticket is closed now. will soon be available.

!!!It is solved in the meantime.

easy fix 

type in a terminal in your home directory

ls -al 

you will see the words root

sudo chown erik ./config -R
sudo chgrp users ./config -R


you are done!


EXTRA'S

AUTOLOGIN ON AUTOLOGIN

https://github.com/Arakis/autologin-on-boot

packer autologin-on-boot --noedit
sudo systemctl enable autologin-on-boot
sudo systemctl start autologin-on-boot

Now set your username to login 

sudo nano  /etc/autologin-on-boot.conf

Make sure your login is on the first line and nothing else

Save via CTRl+X and press "y"
reboot



NVIDIA DRIVERS

sudo pacman -S nvidia   and press a few times on TAB - see on nvidia what number
of driver you should install


DUAL SCREEN
xrandr will tell you the names of your screens
change the config in that regard


CNCHI (if during installation cnchi gives you trouble)

From github :
From the ISO, close Cnchi and run this commands from a terminal:
sudo pacman -S git
sudo rm -rf /usr/share/cnchi
git clone https://github.com/Antergos/cnchi --depth=1
cd cnchi
./run﻿