#!/bin/bash
#              `.-/::/-``
#            .-/osssssssso/.               
#           :osyysssssssyyys+-              
#        `.+yyyysssssssssyyyyy+.           
#       `/syyyyyssssssssssyyyyys-`         
#      `/yhyyyyysss++ssosyyyyhhy/`         
#     .ohhhyyyyso++/+oso+syy+shhhho.       
#    .shhhhysoo++//+sss+++yyy+shhhhs.      
#   -yhhhhs+++++++ossso+++yyys+ohhddy:     
#  -yddhhyo+++++osyyss++++yyyyooyhdddy-    
# .yddddhso++osyyyyys+++++yyhhsoshddddy`   
#`odddddhyosyhyyyyyy++++++yhhhyosddddddo   
#.dmdddddhhhhhhhyyyo+++++shhhhhohddddmmh.  
#ddmmdddddhhhhhhhso++++++yhhhhhhdddddmmdy  
#dmmmdddddddhhhyso++++++shhhhhddddddmmmmh  
#-dmmmdddddddhhyso++++oshhhhdddddddmmmmd- 
# .smmmmddddddddhhhhhhhhhdddddddddmmmms. 
#   `+ydmmmdddddddddddddddddddmmmmdy/.     
#      `.:+ooyyddddddddddddyyso+:.`
#======================================================================================
#                               I3 IMPROVED TILING
# 
# Author  : Erik Dubois at http://www.erikdubois.be
# License : Distributed under the terms of GNU GPL version 2 or later
# 
# AS ALLWAYS, KNOW WHAT YOU ARE DOING.
#======================================================================================
#                               
# Interesting Sources : 
#
# https://i3wm.org/docs/userguide.html
# https://github.com/Arakis/autologin-on-boot
#
#======================================================================================

# Made to be installed on a BASE ANTERGOS
# no desktop environment, no display manager - X11 not yet installed
# all kinds of programs are being used from different distro's but xfce4 is my preference.

1 KEYBOARD

sudo loadkey be-latin1    in order to have azerty KEYBOARD

change also the following file to make it permanent

sudo nano /etc/vconsole.conf

change your keyboard from "be"  to "be-latin1"




2 INTERNET

no internet on lan 

sudo systemctl enable dhcpcd
sudo systemctl start dhcpcd



3 GET GIT 

sudo pacman -S git




4 Downloading my settings from github

git clone https://github.com/erikdubois/i3wmarchdark




5 Move this directory to the right place

cp -r ~/i3wmarchdark/ ~/.i3/




6 installation of software

~/.i3/installation/install i3_vxx.sh

First part is all software in normal arch repo's.
Second part is all software from aur repo's.

########

A T T E N T I O N !!

At the moment of writing I am trying out i3-gaps-next available via aur and
can be found on github.

That's why we first install i3-wm and uninstall it lateron to get the "gaps" version.
Evaluate what you think is best.


##########

7 Let linux know where the most important documents are

# depending on how far you are in your installation some of these files
# will not yet exist - you can not remove what is not there
# ignore the errors

~/.i3/installation/keep_all_here_vx

# .xinitrc is the most important as it says to start i3 to the xserver.


8 Change appearance

windowskey or Mod1 and d opens the menu

type  "lx"  and choose lxappearance
change to your liking



9 Font 

move the font to its right directory

mkdir ~/.fonts    #if necessary make directory First
cp ~/.i3/installation/fonts/fontawesome-webfont.ttf ~/.fonts/


10 Config apps

here are my personal preferences or plugins or ... 
use them or not
these are not essential to the installation


11 Change the look for qt4 applications

mod1+d and look for the program "qt4-configqt4"
programs like spotify will change their submenu's to the qtk theme
choose same font as rest or a different one.


12 .config directory is owned by root 

a ticket has been filed at github regarding this matter

easy fix 

type in a terminal in your home directory

ls -al 

you will see the words root

sudo chown erik ./config -R
sudo chgrp users ./config -R


you are done!


EXTRA'S

AUTOLOGIN ON AUTOLOGIN

https://github.com/Arakis/autologin-on-boot

packer autologin-on-boot --noedit
sudo systemctl enable autologin-on-boot
sudo systemctl start autologin-on-boot

Now set your username to login 

sudo nano  /etc/autologin-on-boot.conf

Make sure your login is on the first line and nothing else

Save via CTRl+X and press "y"
reboot



NVIDIA DRIVERS

sudo pacman -S nvidia   and press a few times on TAB - see on nvidia what number
of driver you should install


DUAL SCREEN
xrandr will tell you the names of your screens
change the config in that regard
